import { FormEvent, useState } from "react";
import { BadgeCheck, BriefcaseMedical, Clock3, Languages, MapPin, Moon, Save, Stethoscope, Sun, UserRound } from "lucide-react";
import { api } from "../services/api";
import { useAsyncData } from "../hooks/useAsyncData";
import { useApp } from "../contexts/AppContext";
import { toast } from "sonner@2.0.3";

export function DoctorProfileSettings({ onProfileUpdated }: { onProfileUpdated?: (user: any) => void }) {
  const { language, dir, theme, toggleTheme, toggleLanguage } = useApp(); const ar = language === "ar";
  const { data, setData, isLoading, error } = useAsyncData(() => api.doctorProfile(), []); const [saving, setSaving] = useState(false);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); const form = new FormData(event.currentTarget); try { const updated = await api.updateDoctorProfile({ name: form.get("name"), phone: form.get("phone"), specialty: form.get("specialty"), experience: Number(form.get("experience") || 0), clinic: form.get("clinic"), address: form.get("address"), workHours: form.get("workHours"), fee: Number(form.get("fee") || 0), consultationType: form.get("consultationType"), isAvailableForVideo: form.get("consultationType") !== "clinic" }); setData(updated); onProfileUpdated?.(updated.user); toast.success(ar ? "تم حفظ بياناتك" : "Profile saved"); } catch (error) { toast.error(error instanceof Error ? error.message : "Error"); } finally { setSaving(false); } }
  if (isLoading) return <div className="workspace-empty"><div className="loading-spinner" /></div>; if (error) return <div className="workspace-empty">{error}</div>;
  return <div className="doctor-settings workspace-page" dir={dir}><header className="workspace-page-head"><div><span>{ar ? "الحساب والإعدادات" : "Account & settings"}</span><h2>{ar ? "ملفي الشخصي" : "My profile"}</h2><p>{ar ? "حدّث بياناتك المهنية وطريقة ظهورك للمرضى." : "Update professional information shown to patients."}</p></div><span className="verified-doctor"><BadgeCheck />{ar ? "طبيب موثق" : "Verified doctor"}</span></header>
    <div className="settings-layout"><aside className="doctor-profile-card"><span className="doctor-profile-avatar">{data?.user?.name?.slice(0,1)}</span><h3>{data?.user?.name}</h3><p>{data?.specialty}</p><div><span><BriefcaseMedical />{data?.experience} {ar ? "سنوات خبرة" : "years experience"}</span><span><MapPin />{data?.clinic}</span><span><Clock3 />{data?.workHours}</span></div></aside>
      <form className="settings-form" onSubmit={save} key={data?._id}><section className="settings-section"><div className="settings-section-title"><span><UserRound /></span><div><h3>{ar ? "البيانات الأساسية" : "Basic information"}</h3><p>{ar ? "بيانات التواصل والهوية المهنية." : "Contact and professional identity."}</p></div></div><div className="settings-grid"><label><span>{ar ? "الاسم" : "Name"}</span><input name="name" defaultValue={data?.user?.name} required /></label><label><span>{ar ? "رقم الهاتف" : "Phone"}</span><input name="phone" defaultValue={data?.user?.phone} dir="ltr" /></label><label><span>{ar ? "التخصص" : "Specialty"}</span><input name="specialty" defaultValue={data?.specialty} required /></label><label><span>{ar ? "سنوات الخبرة" : "Experience"}</span><input name="experience" type="number" min="0" defaultValue={data?.experience} /></label></div></section>
        <section className="settings-section"><div className="settings-section-title"><span><Stethoscope /></span><div><h3>{ar ? "بيانات العيادة" : "Practice details"}</h3><p>{ar ? "مكان العمل والتكلفة ومواعيد التواجد." : "Location, fees and availability."}</p></div></div><div className="settings-grid"><label><span>{ar ? "اسم العيادة" : "Clinic"}</span><input name="clinic" defaultValue={data?.clinic} /></label><label><span>{ar ? "سعر الكشف" : "Consultation fee"}</span><input name="fee" type="number" min="0" defaultValue={data?.fee} /></label><label className="settings-wide"><span>{ar ? "العنوان" : "Address"}</span><input name="address" defaultValue={data?.address} /></label><label><span>{ar ? "ساعات العمل" : "Working hours"}</span><input name="workHours" defaultValue={data?.workHours} /></label><label><span>{ar ? "نوع الاستشارة" : "Consultation type"}</span><select name="consultationType" defaultValue={data?.consultationType}><option value="clinic">{ar ? "عيادة فقط" : "Clinic only"}</option><option value="video">{ar ? "فيديو فقط" : "Video only"}</option><option value="both">{ar ? "عيادة وفيديو" : "Clinic & video"}</option></select></label></div></section><button className="settings-save" disabled={saving}><Save />{saving ? (ar ? "جارٍ الحفظ..." : "Saving...") : (ar ? "حفظ التغييرات" : "Save changes")}</button></form>
    </div><section className="preference-card"><div><span><Moon /></span><div><h3>{ar ? "المظهر واللغة" : "Appearance & language"}</h3><p>{ar ? "تغييرات محفوظة على هذا الجهاز." : "Preferences saved on this device."}</p></div></div><div><button onClick={toggleTheme}>{theme === "light" ? <Moon /> : <Sun />}{theme === "light" ? (ar ? "الوضع الداكن" : "Dark mode") : (ar ? "الوضع الفاتح" : "Light mode")}</button><button onClick={toggleLanguage}><Languages />{ar ? "English" : "العربية"}</button></div></section>
  </div>;
}
