import { CalendarCheck2, Check, ChevronLeft, ChevronRight, Clock3, FilePlus2, Stethoscope, UserRound, UsersRound, Video } from "lucide-react";
import { ApiUser,api } from "../services/api";import { useAsyncData } from "../hooks/useAsyncData";import { useApp } from "../contexts/AppContext";import { toast } from "sonner@2.0.3";
interface Props{onLogout:()=>void;onNavigate?:(s:string)=>void;currentUser?:ApiUser|null}
export function DoctorDashboard({onLogout,onNavigate,currentUser}:Props){const {language}=useApp();const ar=language==="ar";const {data:appointments,setData:setAppointments}=useAsyncData(()=>api.appointments(),[]);const {data:patients}=useAsyncData(()=>api.patients(),[]);const today=new Date().toISOString().slice(0,10);const todays=(appointments||[]).filter((a:any)=>String(a.date).slice(0,10)===today);const upcoming=(appointments||[]).filter((a:any)=>String(a.date).slice(0,10)>today);const Arrow=ar?ChevronLeft:ChevronRight;
 async function update(id:string,status:string){try{const item=await api.updateAppointment(id,{status});setAppointments((appointments||[]).map((a:any)=>a._id===id?{...a,...item}:a));toast.success(ar?"تم تحديث الموعد":"Appointment updated")}catch(e){toast.error(e instanceof Error?e.message:"Error")}}
 return <div className="dashboard-content"><section className="welcome-row"><div><span>{ar?"مرحبًا دكتور":"Welcome doctor"}</span><h2>{currentUser?.name}</h2><p>{ar?`لديك ${todays.length} مواعيد في جدول اليوم.`:`You have ${todays.length} appointments on today's schedule.`}</p></div><button className="primary-action" onClick={()=>onNavigate?.("prescription")}><FilePlus2/>{ar?"روشتة جديدة":"New prescription"}</button></section>
 <div className="stat-strip"><div><span><CalendarCheck2/></span><p>{ar?"مواعيد اليوم":"Today"}<b>{todays.length}</b></p></div><div><span><UsersRound/></span><p>{ar?"إجمالي المرضى":"Patients"}<b>{(patients||[]).length}</b></p></div><div><span><Video/></span><p>{ar?"استشارات الفيديو":"Video visits"}<b>{(appointments||[]).filter((a:any)=>a.type==="video").length}</b></p></div><div><span><Clock3/></span><p>{ar?"مواعيد قادمة":"Upcoming"}<b>{upcoming.length}</b></p></div></div>
 <div className="dashboard-two-col doctor-layout"><section className="surface-card"><div className="section-heading"><div><span className="section-kicker">{ar?"جدول العيادة":"Clinic schedule"}</span><h3>{ar?"مواعيد اليوم":"Today's appointments"}</h3></div><span className="date-chip">{new Date().toLocaleDateString(ar?"ar-EG":"en-US",{day:"numeric",month:"long"})}</span></div><div className="schedule-list">{todays.length?todays.map((a:any)=><div className="schedule-row" key={a._id}><time>{a.time}</time><span className="patient-avatar">{a.patient?.name?.[0]}</span><div><b>{a.patient?.name}</b><small>{a.type==="video"?(ar?"استشارة مرئية":"Video consultation"):(ar?"زيارة عيادة":"Clinic visit")}</small></div><span className={`status-dot status-${a.status}`}>{a.status}</span>{a.status!=="completed"&&<button onClick={()=>update(a._id,"completed")} title="complete"><Check/></button>}</div>):<div className="empty-state">{ar?"لا توجد مواعيد اليوم":"No appointments today"}</div>}</div></section>
 <section className="surface-card"><div className="section-heading"><div><span className="section-kicker">{ar?"آخر النشاط":"Recent activity"}</span><h3>{ar?"المرضى الحاليون":"Current patients"}</h3></div><button className="text-action" onClick={()=>onNavigate?.("patient-files")}>{ar?"عرض الكل":"View all"}</button></div><div className="patient-list">{(patients||[]).slice(0,5).map((p:any)=><button key={p._id} onClick={()=>onNavigate?.("patient-files")}><span className="patient-avatar"><UserRound/></span><div><b>{p.user?.name}</b><small>{p.condition|| (ar?"متابعة عامة":"General follow-up")}</small></div><span className={`patient-state ${p.status}`}>{p.status}</span><Arrow/></button>)}</div></section></div>
 <section className="doctor-actions"><button onClick={()=>onNavigate?.("doctor-video-consultation")}><span><Video/></span><div><b>{ar?"غرفة الاستشارات":"Consultation room"}</b><small>{ar?"ابدأ أو تابع مكالمات الفيديو":"Start or continue video calls"}</small></div><Arrow/></button><button onClick={()=>onNavigate?.("patient-files")}><span><UsersRound/></span><div><b>{ar?"ملفات المرضى":"Patient records"}</b><small>{ar?"تاريخ طبي وبيانات المتابعة":"History and follow-up data"}</small></div><Arrow/></button><button onClick={()=>onNavigate?.("prescription")}><span><Stethoscope/></span><div><b>{ar?"كتابة روشتة":"Write prescription"}</b><small>{ar?"تشخيص وخطة علاج جديدة":"Diagnosis and treatment plan"}</small></div><Arrow/></button></section>
 </div>}
