import { CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, FileText, HeartPulse, MapPin, Pill, ShoppingBag, Stethoscope, Video } from "lucide-react";
import { ApiUser, api } from "../services/api";
import { useAsyncData } from "../hooks/useAsyncData";
import { useApp } from "../contexts/AppContext";
import { toast } from "sonner@2.0.3";

interface Props{onLogout:()=>void;onNavigate?:(s:string)=>void;currentUser?:ApiUser|null}
export function PatientDashboard({onLogout,onNavigate,currentUser}:Props){
 const {language}=useApp();const ar=language==="ar";
 const {data:appointments}=useAsyncData(()=>api.appointments(),[]);const {data:schedules,setData:setSchedules}=useAsyncData(()=>api.medicationSchedules(),[]);const {data:profile}=useAsyncData(()=>api.patientProfile(),[]);const {data:prescriptions}=useAsyncData(()=>api.prescriptions(),[]);
 const next=(appointments||[]).filter((a:any)=>a.status!=="cancelled"&&a.status!=="completed")[0];
 const doses=(schedules||[]).flatMap((s:any)=>s.times.map((time:string)=>({...s,time,taken:s.takenToday?.includes(time)})));
 async function take(schedule:any,time:string){try{const updated=await api.updateMedicationSchedule(schedule._id,{takenToday:Array.from(new Set([...(schedule.takenToday||[]),time]))});setSchedules((schedules||[]).map((s:any)=>s._id===updated._id?updated:s));toast.success(ar?"تم تسجيل الجرعة":"Dose recorded")}catch(e){toast.error(e instanceof Error?e.message:"Error")}}
 const Arrow=ar?ChevronLeft:ChevronRight;
 return <div className="dashboard-content">
   <section className="welcome-row"><div><span>{ar?"صباح الخير":"Good morning"}</span><h2>{currentUser?.name?.split(" ")[0]}، {ar?"نتمنى لك يومًا صحيًا":"wishing you a healthy day"}</h2><p>{ar?"لديك ملخص رعايتك ومهامك الصحية لليوم.":"Here is your care summary and today's health tasks."}</p></div><button className="primary-action" onClick={()=>onNavigate?.("appointment-booking")}><CalendarDays/>{ar?"حجز موعد جديد":"Book appointment"}</button></section>
   <div className="patient-hero-grid"><section className="next-appointment"><div className="section-heading"><div><span className="section-kicker">{ar?"الموعد القادم":"Next appointment"}</span><h3>{next?new Date(next.date).toLocaleDateString(ar?"ar-EG":"en-US",{weekday:"long",day:"numeric",month:"long"}):(ar?"لا يوجد موعد قادم":"No upcoming appointment")}</h3></div><span className="status-pill">{next?.status==="confirmed"?(ar?"مؤكد":"Confirmed"):(ar?"قيد التأكيد":"Pending")}</span></div>{next&&<div className="appointment-person"><span className="doctor-avatar"><Stethoscope/></span><div><b>{next.doctor?.name}</b><small>{next.doctorProfile?.specialty}</small></div><div className="appointment-meta"><span><Clock3/>{next.time}</span><span><MapPin/>{next.clinic||"Online"}</span></div><button onClick={()=>next.type==="video"&&onNavigate?.("video-consultation")}><Arrow/></button></div>}</section>
    <section className="health-score"><div className="score-ring"><HeartPulse/><b>{profile?.status==="stable"?"92":"86"}</b><small>/ 100</small></div><div><span className="section-kicker">{ar?"مؤشر صحتك":"Health score"}</span><h3>{ar?"حالتك مستقرة":"You're doing well"}</h3><p>{ar?"استمر في الالتزام بالأدوية ومواعيد المتابعة.":"Keep up with medications and follow-ups."}</p></div></section></div>
   <section className="quick-services"><button onClick={()=>onNavigate?.("appointment-booking")}><span><CalendarDays/></span><div><b>{ar?"حجز طبيب":"Book a doctor"}</b><small>{ar?"اختر التخصص والموعد":"Choose specialty and time"}</small></div><Arrow/></button><button onClick={()=>onNavigate?.("video-consultation")}><span><Video/></span><div><b>{ar?"استشارة مرئية":"Video consultation"}</b><small>{ar?"تواصل مع طبيب الآن":"Speak to a doctor now"}</small></div><Arrow/></button><button onClick={()=>onNavigate?.("pharmacy-delivery")}><span><ShoppingBag/></span><div><b>{ar?"طلب من الصيدلية":"Pharmacy order"}</b><small>{ar?"أدويتك حتى باب البيت":"Medication delivered"}</small></div><Arrow/></button></section>
   <div className="dashboard-two-col"><section className="surface-card"><div className="section-heading"><div><span className="section-kicker">{ar?"خطة اليوم":"Today's plan"}</span><h3>{ar?"مواعيد الأدوية":"Medication schedule"}</h3></div><button className="text-action" onClick={()=>onNavigate?.("medication-reminder")}>{ar?"إدارة الأدوية":"Manage"}</button></div><div className="dose-list">{doses.length?doses.slice(0,4).map((d:any)=><div className={d.taken?"dose-row is-done":"dose-row"} key={`${d._id}-${d.time}`}><span className="dose-icon"><Pill/></span><div><b>{d.medicationName}</b><small>{d.dosage}</small></div><time>{d.time}</time><button disabled={d.taken} onClick={()=>take(d,d.time)}>{d.taken?<Check/>:(ar?"تم":"Take")}</button></div>):<div className="empty-state">{ar?"لا توجد أدوية مضافة":"No medications added"}</div>}</div></section>
    <section className="surface-card"><div className="section-heading"><div><span className="section-kicker">{ar?"المؤشرات الحيوية":"Health metrics"}</span><h3>{ar?"آخر القراءات":"Latest readings"}</h3></div></div><div className="vitals-grid">{(profile?.healthMetrics||[]).slice(0,4).map((m:any)=><div key={m.label}><span>{m.label}</span><b>{m.value}</b><small>{ar?"ضمن المعدل":"In range"}</small></div>)}</div></section></div>
   {(prescriptions||[]).length>0&&<section className="care-plan-card surface-card"><div className="care-plan-icon"><FileText/></div><div><span className="section-kicker">{ar?"آخر خطة علاج":"Latest care plan"}</span><h3>{prescriptions[0].diagnosis}</h3><p>{prescriptions[0].medications?.map((med:any)=>`${med.name} — ${med.dosage}`).join(" • ")}</p></div><div className="care-plan-doctor"><small>{ar?"كتبها":"Prescribed by"}</small><b>{prescriptions[0].doctor?.name}</b><span>{new Date(prescriptions[0].createdAt).toLocaleDateString(ar?"ar-EG":"en-US")}</span></div></section>}
  </div>
}
